name: Deploy Lambda via CDK

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install CDK & dependencies
        run: |
          npm install -g aws-cdk
          pip install -r requirements.txt

      - name: Set AWS credentials as environment variables
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "Setting AWS Credentials"
          # Comando para desplegar
          cd cdk
          cdk deploy --require-approval never
