name: lambda_zip_test
on:
  push:
    paths:
      - "testing-lambda2/**"
jobs:
  lambda_demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID}}
          aws-region: us-east-1
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
           python-version: '3.x'
      -  name: Creating deployment zip
         run: |
          sudo apt install zip
          python -m pip install --upgrade pip
          cd testing-lambda2
          mkdir -p deployment_zip 
          pip install -r requirements.txt -t deployment_zip
          cp lambda_function.py deployment_zip
          cd deployment_zip 
          zip -r lambda_zip.zip *
      - name: lambda_code_update
        run: |
          aws lambda update-function-code --function-name just-another-test-for-practice --zip-file fileb://testing-lambda2/deployment_zip/lambda_zip.zip